### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by mwjames** [JeroenDeDauw/ParamProcessor#37]
param-processor/param-processor: 1.3.4

PHP log has reports of:

```
PHP Warning:  Invalid argument supplied for foreach() in ...\vendor\param-processor\param-processor\src\Param.php on line 172
PHP Warning:  Invalid argument supplied for foreach() in ...\vendor\param-processor\param-processor\src\Param.php on line 262
PHP Warning:  explode() expects parameter 2 to be string, array given in ...\vendor\param-processor\param-processor\src\Param.php on line 169

```

**Comment by JeroenDeDauw** [comment]
Not enough info to tell if this issue is wit ParamProcessor or the caller.

As with https://github.com/JeroenDeDauw/ParamProcessor/issues/36 it seems like a parameter value is an array at a point where it should not be. Perhaps the calling code is incorrectly assuming it can provide an array where it should be providing a string?

**Comment by mwjames** [comment]
> Not enough info to tell if this issue is wit ParamProcessor or the caller.

I'm fairly aware of that and I said I found that in the PHP log so I
don't know the context but I thought I'm a good sport and create a
report instead of just ignoring it.

Feel free to ignore it, close it, or deal with it as you see fit.
